### ISSUE TITLE
Need to specify exact getField

### ISSUE THREAD

**Issue by chiroptical** [chiroptical/derive-has-field#7]
https://github.com/chiroptical/derive-has-field/blob/14db598daaddee372ea6b3f4ab65b96e95390aeb/src/DeriveHasField.hs#L62

This forced `getField` to be in scope. We need to get the exact name.

**Comment by chiroptical** [comment]
I think https://hackage.haskell.org/package/template-haskell-2.22.0.0/docs/Language-Haskell-TH.html#v:lookupValueName is what we need.

**Comment by chiroptical** [comment]
In theory, you can write a test that `import DeriveHasField qualified` and it _should_ fail.

**Comment by mpickering** [comment]
Thanks for making this fix. 

If you are interested the `0.0.1.0` version doesn't have a `template-haskell` bound, so if you are not careful then the solver will choose that old version if you are using a very new version of `template-haskell`. If you could make a revision to the `0.0.1.0` version that could be an improvement.

**Comment by chiroptical** [comment]
> Thanks for making this fix.
> 
> If you are interested the `0.0.1.0` version doesn't have a `template-haskell` bound, so if you are not careful then the solver will choose that old version if you are using a very new version of `template-haskell`. If you could make a revision to the `0.0.1.0` version that could be an improvement.

Hey, nice catch. I made an update to the tar download and tried to re-publish but it fails. Are there docs on this somewhere?

**Comment by mpickering** [comment]
@chiroptical Go to the page (https://hackage.haskell.org/package/derive-has-field-0.0.1.0) and click on "edit package information", then you can add the bound.

**Comment by chiroptical** [comment]
> @chiroptical Go to the page (https://hackage.haskell.org/package/derive-has-field-0.0.1.0) and click on "edit package information", then you can add the bound.

Amazing, thank you! This is my first hackage package so I appreciate the pointers!
